//! Chat request / response / streaming event types.

use crate::message::Message;
use crate::sampling::SamplingParams;
use crate::tool::{ToolDescriptor, ToolFilter, ToolOutput};
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// How the harness should handle tool calls emitted by the model.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolExecution {
    /// Harness executes tools itself in a ReAct loop until the model
    /// emits a final assistant message or `max_tool_iterations` is hit.
    #[default]
    Auto,
    /// Harness emits `StreamEvent::ToolCallRequest` and waits for the
    /// host to feed back results via the chat loop. The host is
    /// responsible for executing the tools.
    HostControlled,
}

/// A request to the harness's chat engine.
#[derive(Debug, Clone)]
pub struct ChatRequest {
    /// Conversation history. The harness will append to this as it
    /// iterates (tool calls + tool results) but the original vector
    /// passed in is not mutated.
    pub messages: Vec<Message>,

    /// Specific model to use. None = harness's active model.
    pub model: Option<String>,

    /// Which tools the model may call.
    pub tools: ToolFilter,

    /// Auto vs HostControlled tool execution.
    pub tool_execution: ToolExecution,

    /// Max tool-call iterations before giving up. Default 8.
    pub max_tool_iterations: usize,

    /// Sampling parameters.
    pub sampling: SamplingParams,

    /// Extra stop strings (in addition to model defaults).
    pub stop: Vec<String>,
}

impl Default for ChatRequest {
    fn default() -> Self {
        Self {
            messages: Vec::new(),
            model: None,
            tools: ToolFilter::default(),
            tool_execution: ToolExecution::default(),
            max_tool_iterations: 8,
            sampling: SamplingParams::default(),
            stop: Vec::new(),
        }
    }
}

/// One ReAct iteration's record (for streaming consumers and tracing).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReActStep {
    /// Number of the step (0 = first assistant turn, 1+ = tool follow-ups).
    pub step: usize,
    /// The model's raw output before parsing.
    pub raw_output: String,
    /// Parsed tool calls (empty if the model gave a final answer).
    pub tool_calls: Vec<ToolCallRequest>,
    /// Tool results (empty if no tools were called).
    pub tool_results: Vec<ToolCallResult>,
}

/// A tool call the model wants to make.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallRequest {
    /// Id generated by the harness (UUID v4) for tracing.
    pub id: String,
    /// Name of the tool.
    pub name: String,
    /// Parsed JSON arguments.
    pub arguments: Value,
}

/// The result of executing a tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallResult {
    /// Id of the originating `ToolCallRequest`.
    pub id: String,
    /// Tool name (for logging).
    pub name: String,
    /// Tool output (text + optional structured data).
    pub output: ToolOutput,
}

/// Final response from a chat call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    /// The model's final assistant text (after all tool iterations).
    pub final_text: String,
    /// All assistant turns, in order (text only).
    pub assistant_turns: Vec<String>,
    /// All tool calls made and their results.
    pub trace: Vec<ReActStep>,
    /// Number of prompt tokens consumed.
    pub prompt_tokens: i32,
    /// Number of completion tokens consumed.
    pub completion_tokens: i32,
    /// Stop reason from the final assistant turn.
    pub stop_reason: String,
    /// Tool descriptors that were visible to the model.
    pub tools_used: Vec<ToolDescriptor>,
}

/// Streaming event emitted while a chat call is in progress.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum StreamEvent {
    /// A raw token from the model.
    Token {
        /// Token text (decoded piece; may be empty on token-id-only frames).
        text: String,
    },

    /// The model has emitted one or more tool calls (before they run).
    ToolCallStart {
        /// All calls in this batch.
        calls: Vec<ToolCallRequest>,
    },

    /// Tool result is ready.
    ToolExecuted {
        /// The result.
        result: ToolCallResult,
    },

    /// All done. Final response follows.
    Done(ChatResponse),

    /// Stream was cancelled.
    Cancelled,

    /// Error during the stream.
    Error(String),
}

impl std::fmt::Display for StreamEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StreamEvent::Token { text } => write!(f, "Token({:?})", text),
            StreamEvent::ToolCallStart { calls } => {
                write!(f, "ToolCallStart({} calls)", calls.len())
            }
            StreamEvent::ToolExecuted { result } => {
                write!(f, "ToolExecuted({})", result.name)
            }
            StreamEvent::Done(_) => write!(f, "Done"),
            StreamEvent::Cancelled => write!(f, "Cancelled"),
            StreamEvent::Error(s) => write!(f, "Error({})", s),
        }
    }
}

/// Role of a `Message` -- re-exported for callers that want to build
/// messages without importing the full `Message` constructor module.
pub use crate::message::Role as ChatRole;
